language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --no-dev
  - curl -LSs https://github.com/box-project/box2/releases/download/2.5.2/box-2.5.2.phar
  - mv box-2.5.2.phar box.phar
  - chmod +x box.phar

script: 
  - phpunit
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then php box.phar build; php spress.phar --version; fi

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0957171278778ab21da9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
